/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_setl_ed25519_Ed25519DonnaJNI */

#ifndef _Included_com_setl_ed25519_Ed25519DonnaJNI
#define _Included_com_setl_ed25519_Ed25519DonnaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_setl_ed25519_Ed25519DonnaJNI
 * Method:    testCryptoLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_setl_ed25519_Ed25519DonnaJNI_testCryptoLibrary
  (JNIEnv *, jobject);

/*
 * Class:     com_setl_ed25519_Ed25519DonnaJNI
 * Method:    createRandomBytes
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_setl_ed25519_Ed25519DonnaJNI_createRandomBytes
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_setl_ed25519_Ed25519DonnaJNI
 * Method:    createPublicKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_setl_ed25519_Ed25519DonnaJNI_createPublicKey
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_setl_ed25519_Ed25519DonnaJNI
 * Method:    createSignature
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_setl_ed25519_Ed25519DonnaJNI_createSignature
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_setl_ed25519_Ed25519DonnaJNI
 * Method:    verifySignature
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_setl_ed25519_Ed25519DonnaJNI_verifySignature
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_setl_ed25519_Ed25519DonnaJNI
 * Method:    batchVerifySignature
 * Signature: ([[B[I[[B[[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_setl_ed25519_Ed25519DonnaJNI_batchVerifySignature
  (JNIEnv *, jobject, jobjectArray, jintArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
